from QuoteEngine.DocxIngestor import DocxIngestor
from QuoteEngine.CSVIngestor import CSVIngestor
from QuoteEngine.PDFIngestor import PDFIngestor
from QuoteEngine.TextIngestor import TextIngestor
from QuoteEngine.IngestorInterface import IngestorInterface
from QuoteEngine.Ingestor import Ingestor